version: "3.8"

services:
  vector_db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  ai_backend:
    build: ./services/ai_backend
    ports:
      - "8000:8000"
    depends_on:
      - vector_db
      - ollama
    restart: unless-stopped

  frontend_chat:
    build: ./services/frontend_chat
    ports:
      - "8501:8501"
    depends_on:
      - ai_backend
    restart: unless-stopped

volumes:
  qdrant_data:
  ollama_data:
